version: '3.7'
services:

  product_db:
    image: postgres:17
    hostname: product_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products_db
      SCHEMA_NAME: products
    ports:
      - "5432:5432"
